"""Selector back to transaction

Revision ID: 28556ab17c56
Revises: e455c78df789
Create Date: 2023-01-23 00:34:39.062562+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "28556ab17c56"
down_revision = "e455c78df789"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("tags", "tagged", schema="transactions")
    op.create_table(
        "selector",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "selector",
            sa.Enum(
                "unknown",
                "nullifier",
                "vacations",
                "rules",
                "algorithm",
                "manual",
                name="selector_t",
                schema="transactions",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["transactions.categorized.id"],
            name=op.f("fk_selector_id_categorized"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_selector")),
        schema="transactions",
    )
    op.drop_table("selector", schema="category")

    op.rename_table("originals", "transactions", schema="transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("transactions", "originals", schema="transactions")

    op.create_table(
        "selector",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "selector",
            postgresql.ENUM(
                "unknown",
                "nullifier",
                "vacations",
                "rules",
                "algorithm",
                "manual",
                name="selector_t",
                schema="category",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["transactions.categorized.id"],
            name="fk_selector_id_categorized",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_selector"),
        schema="category",
    )
    op.drop_table("selector", schema="transactions")
    op.rename_table("tagged", "tags", schema="transactions")
    # ### end Alembic commands ###
