"""Available categories and rules

Revision ID: 2d0891f1be11
Revises: 287fe9e6682a
Create Date: 2022-12-04 11:15:22.758487+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d0891f1be11"
down_revision = "287fe9e6682a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories_available",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_categories_available")),
        schema="transactions",
    )
    op.create_table(
        "categories_rules",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("rule", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["name"],
            ["transactions.categories_available.name"],
            name=op.f("fk_categories_rules_name_categories_available"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("name", "rule", name=op.f("pk_categories_rules")),
        schema="transactions",
    )
    op.alter_column("categorized", "category", new_column_name="name", schema="transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categorized", "name", new_column_name="category", schema="transactions")
    op.drop_table("categories_rules", schema="transactions")
    op.drop_table("categories_available", schema="transactions")
    # ### end Alembic commands ###
