"""Rule min/max

Revision ID: 753c0bfb2062
Revises: e36e6321568e
Create Date: 2022-12-18 00:24:03.861461+00:00

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "753c0bfb2062"
down_revision = "e36e6321568e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories_rules",
        "min_amount",
        new_column_name="min",
        schema="transactions",
    )
    op.alter_column(
        "categories_rules",
        "max_amount",
        new_column_name="max",
        schema="transactions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories_rules",
        "min",
        new_column_name="min_amount",
        schema="transactions",
    )
    op.alter_column(
        "categories_rules",
        "max",
        new_column_name="max_amount",
        schema="transactions",
    )
    # ### end Alembic commands ###
