"""Category rule date format

Revision ID: 7adf89ec8d14
Revises: 83603bb7ef9c
Create Date: 2022-12-10 00:08:47.535765+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7adf89ec8d14"
down_revision = "83603bb7ef9c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories_rules",
        "date",
        existing_type=sa.VARCHAR(),
        type_=sa.Date(),
        existing_nullable=True,
        schema="transactions",
        postgresql_using="date::date"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories_rules",
        "date",
        existing_type=sa.Date(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        schema="transactions",
    )
    # ### end Alembic commands ###
