"""Amount of transaction per period

Revision ID: 83603bb7ef9c
Revises: 8b5d5fbc8211
Create Date: 2022-12-09 23:12:15.644758+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83603bb7ef9c"
down_revision = "8b5d5fbc8211"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories_schedules",
        sa.Column("amount", sa.Integer(), nullable=True),
        schema="transactions",
    )
    op.drop_column("categories_schedules", "recurring", schema="transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories_schedules",
        sa.Column("recurring", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="transactions",
    )
    op.drop_column("categories_schedules", "amount", schema="transactions")
    # ### end Alembic commands ###
