"""Category groups and relationships

Revision ID: 83f4c9837f6e
Revises: 2d0891f1be11
Create Date: 2022-12-04 15:10:51.924875+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83f4c9837f6e"
down_revision = "2d0891f1be11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories_groups",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_categories_groups")),
        schema="transactions",
    )
    op.add_column(
        "categories_available",
        sa.Column("group", sa.String(), nullable=True),
        schema="transactions",
    )
    op.create_foreign_key(
        op.f("fk_categories_available_group_categories_groups"),
        "categories_available",
        "categories_groups",
        ["group"],
        ["name"],
        source_schema="transactions",
        referent_schema="transactions",
    )
    op.create_foreign_key(
        op.f("fk_categorized_name_categories_available"),
        "categorized",
        "categories_available",
        ["name"],
        ["name"],
        source_schema="transactions",
        referent_schema="transactions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_categorized_name_categories_available"),
        "categorized",
        schema="transactions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_categories_available_group_categories_groups"),
        "categories_available",
        schema="transactions",
        type_="foreignkey",
    )
    op.drop_column("categories_available", "group", schema="transactions")
    op.drop_table("categories_groups", schema="transactions")
    # ### end Alembic commands ###
