"""Compact category selector

Revision ID: 8623e709e111
Revises: ce68ee15e5d2
Create Date: 2023-05-08 19:00:51.063240+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8623e709e111"
down_revision = "ce68ee15e5d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("category_selectors", schema="pfbudget")
    op.add_column(
        "transactions_categorized",
        sa.Column(
            "selector",
            sa.Enum(
                "unknown",
                "nullifier",
                "vacations",
                "rules",
                "algorithm",
                "manual",
                name="selector_t",
                schema="pfbudget",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        schema="pfbudget",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions_categorized", "selector", schema="pfbudget")
    op.create_table(
        "category_selectors",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "selector",
            postgresql.ENUM(
                "unknown",
                "nullifier",
                "vacations",
                "rules",
                "algorithm",
                "manual",
                name="selector_t",
                schema="pfbudget",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["pfbudget.transactions_categorized.id"],
            name="fk_category_selectors_id_transactions_categorized",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_category_selectors"),
        schema="pfbudget",
    )
    # ### end Alembic commands ###
