"""Links

Revision ID: 8cc9870b0d74
Revises: a910e1b2214d
Create Date: 2022-12-19 22:10:25.136479+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8cc9870b0d74"
down_revision = "a910e1b2214d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("original", sa.BigInteger(), nullable=False),
        sa.Column("link", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["link"],
            ["transactions.originals.id"],
            name=op.f("fk_links_link_originals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["original"],
            ["transactions.originals.id"],
            name=op.f("fk_links_original_originals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("original", "link", name=op.f("pk_links")),
        schema="transactions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("links", schema="transactions")
    # ### end Alembic commands ###
