"""Tag rules

Revision ID: 9028b0f3b985
Revises: 753c0bfb2062
Create Date: 2022-12-18 22:53:13.334046+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9028b0f3b985"
down_revision = "753c0bfb2062"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags_available",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_tags_available")),
        schema="transactions",
    )
    op.create_table(
        "tag_rules",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("regex", sa.String(), nullable=True),
        sa.Column("bank", sa.String(), nullable=True),
        sa.Column("min", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("max", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag"],
            ["transactions.tags_available.name"],
            name=op.f("fk_tag_rules_tag_tags_available"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag_rules")),
        schema="transactions",
    )
    op.create_foreign_key(
        op.f("fk_tags_tag_tags_available"),
        "tags",
        "tags_available",
        ["tag"],
        ["name"],
        source_schema="transactions",
        referent_schema="transactions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_tags_tag_tags_available"),
        "tags",
        schema="transactions",
        type_="foreignkey",
    )
    op.drop_table("tag_rules", schema="transactions")
    op.drop_table("tags_available", schema="transactions")
    # ### end Alembic commands ###
