"""Start/End date rule

Revision ID: 952de57a3c43
Revises: 18572111d9ff
Create Date: 2023-02-06 21:57:57.545327+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "952de57a3c43"
down_revision = "18572111d9ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rules", sa.Column("start", sa.Date(), nullable=True), schema="transactions"
    )
    op.alter_column("rules", column_name="date", new_column_name="end", schema="transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rules", column_name="end", new_column_name="date", schema="transactions")
    op.drop_column("rules", "start", schema="transactions")
    # ### end Alembic commands ###
