"""Rule inheritance

Revision ID: a910e1b2214d
Revises: 9028b0f3b985
Create Date: 2022-12-19 20:48:04.682812+00:00

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "a910e1b2214d"
down_revision = "9028b0f3b985"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_categorized_name_categories_available",
        "categorized",
        schema="transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_categorized_name_categories_available"),
        "categorized",
        "categories_available",
        ["name"],
        ["name"],
        source_schema="transactions",
        referent_schema="transactions",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_categorized_name_categories_available"),
        "categorized",
        schema="transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_categorized_name_categories_available",
        "categorized",
        "categories_available",
        ["name"],
        ["name"],
        source_schema="transactions",
        referent_schema="transactions",
    )
    # ### end Alembic commands ###
