"""Category schedule

Revision ID: d18cbd50f7c6
Revises: 6863dda76ea2
Create Date: 2022-12-08 13:30:29.048811+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d18cbd50f7c6"
down_revision = "6863dda76ea2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories_schedules",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column(
            "period",
            sa.Enum(
                "daily",
                "monthly",
                "yearly",
                name="period",
                schema="transactions",
                inherit_schema=True,
            ),
            nullable=True,
        ),
        sa.Column("period_multiplier", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["name"],
            ["transactions.categories_available.name"],
            name=op.f("fk_categories_schedules_name_categories_available"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_categories_schedules")),
        schema="transactions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("categories_schedules", schema="transactions")
    # ### end Alembic commands ###
